# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: fetch_build_push_image

on:
  workflow_call:
    inputs:
      source_repository:
        description: 'Repository to fetch'
        required: true
        type: string
      source_branch:
        description: 'Branch to fetch'
        required: false
        default: 'main'
        type: string
      source_dockerfile:
        description: 'Dockerfile to use'
        required: false
        default: 'Dockerfile'
        type: string
      source_build_context:
        description: 'Build context to use'
        required: false
        default: '.'
        type: string
      source_build_args:
        description: 'List of build-time variables'
        required: false
        default: ''
        type: string
      target_architecture:
        description: 'Architecture to fetch'
        required: false
        default: 'linux/amd64'
        type: string
      target_image:
        description: 'Full path, name and tag of the target image'
        required: true
        type: string
      target_registry:
        description: 'Registry to push the image to'
        required: false
        default: ''
        type: string
      target_registry_username:
        description: 'Username for the registry'
        required: false
        default: ''
        type: string


    secrets:
      target_registry_password:
        description: 'Password for the registry'
        required: false

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.source_repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ inputs.source_branch }}
        submodules: 'true'

    - name: Docker Login
      if: ${{ inputs.target_registry != '' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.target_registry }}
        username: ${{ inputs.target_registry_username }}
        password: ${{ secrets.target_registry_password }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.source_dockerfile }}
        push: ${{ inputs.target_registry != '' }}
        tags: ${{ inputs.target_image }}
        platforms: ${{ inputs.target_architecture }}
        build-args: |
          ${{ inputs.source_build_args }}